spring.application.name=AuthService


server.port=2220

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/login
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none   
spring.jpa.show-sql=true

# Format SQL (optional)
spring.jpa.properties.hibernate.format_sql=true
