spring.application.name=ORDERSERVICE
# Server port (optional)
server.port=2222

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/order_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none   
spring.jpa.show-sql=true

# Format SQL (optional)
spring.jpa.properties.hibernate.format_sql=true

# Connection Pool (HikariCP - default in Spring Boot)
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.minimum-idle=5
#spring.datasource.hikari.idle-timeout=30000

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka